use covid19_vaccine_records;

DROP TABLE IF EXISTS address;
DROP TABLE IF EXISTS contact;
SET FOREIGN_KEY_CHECKS=0; DROP TABLE  IF EXISTS dose_1; SET FOREIGN_KEY_CHECKS=1;
SET FOREIGN_KEY_CHECKS=0; DROP TABLE IF EXISTS dose_2; SET FOREIGN_KEY_CHECKS=1;
SET FOREIGN_KEY_CHECKS=0; DROP TABLE IF EXISTS booster; SET FOREIGN_KEY_CHECKS=1;
SET FOREIGN_KEY_CHECKS=0; DROP TABLE IF EXISTS medical_history; SET FOREIGN_KEY_CHECKS=1;
SET FOREIGN_KEY_CHECKS=0; DROP TABLE IF EXISTS primary_physician; SET FOREIGN_KEY_CHECKS=1;
SET FOREIGN_KEY_CHECKS=0; DROP TABLE IF EXISTS patient; SET FOREIGN_KEY_CHECKS=1;
